using BG3_XP_Table_Generator.Converters;
using DevExpress.Mvvm.UI.Interactivity;
using DevExpress.Xpf.LayoutControl;
using System;
using System.Linq;
using System.Windows.Data;

namespace BG3_XP_Table_Generator.Behaviors {
    public class DataLayoutControlGeneratorBehavior : Behavior<DataLayoutControl> {

        private void OnAutoGeneratedGroup(object sender, DataLayoutControlAutoGeneratedGroupEventArgs e) {
            if (e.Group.Header.ToString().Contains("Custom"))
                BindingOperations.SetBinding(e.Group, System.Windows.UIElement.IsEnabledProperty, new Binding(nameof(XPData.Progression)) { Source = DataLayoutControl.CurrentItem, Converter = new ProgressionTypeToBooleanConverter() });
        }

        DataLayoutControl DataLayoutControl => AssociatedObject;

        protected override void OnAttached() {
            base.OnAttached();

            if (DataLayoutControl != null)
                DataLayoutControl.AutoGeneratedGroup += OnAutoGeneratedGroup;
        }

        protected override void OnDetaching() {
            base.OnDetaching();
        }
    }
}
